### ISSUE TITLE
figure out where join warning is getting thrown

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#113]
must be a dplyr update of some sort - mapvizieR object call throws:

```
left_join_impl(x, y, by$x, by$y) :
  joining factor and character vector, coercing into character vector
```

**Comment by chrishaid** [comment]
They mb had the warning backed in for a while. (An example of be helpful versus strict).  

Clearly we have are joining on toe Colima. That have the same info but differing types.

—

**Comment by almartin82** [comment]
it is in `grade_level_seasonify`.
