### ISSUE TITLE
constraints to enforce on roster

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#122]
we are going to need to enforce some minimal constraints on roster -- this list will probably grow, but for starters: 
1. I think we should have an assumption throughout that there are two columns for student names - `studentfirstlast` and `studentlastfirst`.  
2. We should write helper interactive workflow tools that help the user identify _which_ columns in their data have those fields.
3.  Otherwise we get into the hell of specifying which column has which data as a parameter, which we ran into in MAP-visuals, and that was no fun.

**Comment by almartin82** [comment]
we will need to know a student's name to know what to label individual scatterplots / student detail breakouts.

**Comment by chrishaid** [comment]
Re 1 above:  why not assume that the `studenlastname` and `studernfirstname` and construct the `studentlastfirst` and `studentfirstlast` columns with the mv object's roster?  Or is that what you are suggesting?
