### ISSUE TITLE
haid_plot drops some student names 

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#138]
appears to be happening when students **do** have a start score, but not an end score.  investigating.

**Comment by almartin82** [comment]
ok, it's an issue having to do with the colors for growth identity.  currently we don't have a status for a student whose growth status is `NA` (no endritscore).  we want to preserve the ability to customize growth tiers, so I'm appending NA = 'black' to whatever user input we get.

**Comment by chrishaid** [comment]
Awesome!  I like that.
