### ISSUE TITLE
All arguments documentation should identify what the arguments expects

### ISSUE THREAD

**Issue by chrishaid** [almartin82/mapvizieR#190]
Similar to issue #189:  Function documentation should make it obvious what is expected by the function.  `roster_to_cdf` is a good example of this.  Currently the documentation doesn't make clear what the `roster_cols` argument expects.  A character vector where column names are quoted? (probably)

**Comment by almartin82** [comment]
I agree with this.  For housekeeping_1, let's clean up the documentation on `roster_to_cdf`.  For any other place where you see this, file an issue, reference back to this design philosophy note, and we'll attack them as we see it.
