### ISSUE TITLE
should we replace our 'checks' with `ensure_that`?

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#20]
see the vignette [here](https://github.com/smbache/ensurer)

we'd just pipe in an 'ensure_cdf' between the data and the work to be done...

magrittr guy (of course!)

**Comment by almartin82** [comment]
i am bad at markdown.

**Comment by chrishaid** [comment]
Yes!!! This is great and super simple.

**Comment by almartin82** [comment]
I nuked `roster_check` functions and replaced them with `ensurer` contracts.  @chrishaid do you think you can take a look at [the commit](https://github.com/almartin82/mapvizieR/commit/845c3da9aeb36ee913d20d77f109c88117a24e1b#diff-e83b0e93a0e8b57ed7f8b2723fbf35cfR35) and do the same thing to [`cdf_check`](https://github.com/almartin82/mapvizieR/blob/ad1a7ee23a2909f6c4b57435d7199a14f7b5ff64/R/cdf_check.R)?  it's a very good hands on introduction to `ensurer`.

**Comment by chrishaid** [comment]
Sure!

**Comment by almartin82** [comment]
closing this one because I think we have settled on `ensurer` as the way to go here.  if you see one that needs to be ported over to ensurer, tag it and we can do these individually.
