### ISSUE TITLE
Shambach tables test supressions

### ISSUE THREAD

**Issue by chrishaid** [almartin82/mapvizieR#207]
@almartin82 I had to suppress most the tests in Shambach tables, mostly because I didn't have a good sense what they needed to look like.  Take a gander at the new `tableGrob` parameterization.  It's a bit clearer what you are doing, by setting background and foreground graphical parameters, rather than passing in a bunch of prefixed parameter names.

**Comment by almartin82** [comment]
resolved this in the historic_recap branch.
