### ISSUE TITLE
calculate CGI and SGP

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#25]
probably on the [growth df functions](https://github.com/almartin82/mapvizieR/blob/master/R/growth_df_prep.R)

**Comment by chrishaid** [comment]
word

**Comment by almartin82** [comment]
resolved by [this](https://github.com/almartin82/mapvizieR/commit/ad1a7ee23a2909f6c4b57435d7199a14f7b5ff64) pull request by @chrishaid; closing.
