### ISSUE TITLE
each named object on mapvizieR should get a class

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#267]
@chrishaid I think this is going to be useful - 
right now `summary` on mapvizieR _actually_ does a _growth_ summary.  but there are multiple different slots on the mapvizieR object - not just growth!

I think that the logical behavior would be for `summary()` to work on `mv$cdf, mv$growth_df` - or any object on the mapvizieR object.  `summary()` applied to `mv` would return back a named list with the summary methods for EACH element.

to get all the oo dispatch stuff to work right I think this means that each thing on the mapvizieR object should get a class - mapvizieR_cdf, mapvizieR_growth_df, etc etc.

what do you think?

**Comment by chrishaid** [comment]
I like this idea!

**Comment by chrishaid** [comment]
💯

**Comment by almartin82** [comment]
ooh, this is exciting!
