### ISSUE TITLE
Add typical and accelerated growth projections data.frams to mapvizier_object

### ISSUE THREAD

**Issue by chrishaid** [almartin82/mapvizieR#27]
These should be long form data.frames that contain rows comprising:
-  studentid
-  measurementscale
-  grade_level_season
-  growth_season
-  simulation_number (this is for any simulated results so we can show projected uncertainty.  [See the map_projector concept](https://kippdata.shinyapps.io/map_projector/] for what this looks like)).
- projected RIT Score.
- projected RIT Score type (i.e., typical or accelerated).
- pointer to testid?
- persistence of  "projects"/goals?
- hold object as promise?  Does this hurt architecture that generates goals and then adds them back to object.

**Comment by almartin82** [comment]
I know a bunch of work got done on this in early feb - @chrishaid can you update this -- maybe close the issue and open a new one that has next set of tasks?

**Comment by almartin82** [comment]
closing this, because we definitely have growth projections on the mv object.  if we have other ideas for extending the growth & projection work, we can open a new issue.
