### ISSUE TITLE
Weird growth norms for one student

### ISSUE THREAD

**Issue by chrishaid** [almartin82/mapvizieR#28]
Check out this record: `norm_matched[10748,]` from the test examples. 
This student has typical, reported, std of growth all set to 0.  

That can't be right?

**Comment by chrishaid** [comment]
It is weirder yet:
`norm_matched %>% filter(std_dev_of_expectation==0)` yields 255 norm_matched records with 0 st_dev

``` R
norm_matched %>% 
    filter(std_dev_of_expectation==0,
            typical_growth==0,
            reported_growth==0) %>%
    nrow
) 
```

yields 255 norm_matched records with 0 everything.

**Comment by almartin82** [comment]
isn't this probably a NA vs 0 problem?  like, where did those norms come from?  are we dead certain they were read in cleanly?

**Comment by chrishaid** [comment]
All students have start RIT scores and it is over three diff't subjects: math, reading, language usage.

**Comment by almartin82** [comment]
right, but have you verified against the original posted NWEA file?

**Comment by chrishaid** [comment]
Ok I've narrowed it down a little bit more:

All students have a start_grade of 10 and an end_grade of either 11 or NA
and growth_window si spring to spring

**Comment by chrishaid** [comment]
Uhhhg.  Sure enough the norms data has 0, 0 ,0  for thos students spring to spring.  Like, wtf is that NWEA.

**Comment by almartin82** [comment]
If this is NWEA's fault I think we are closing as `wontfix` :smiley_cat:
