### ISSUE TITLE
is.ggplot() is not a useful test

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#34]
I think this because of the weak class system in S3? in any case `is.ggplot()` doesn't ensure that you have a valid ggplot object  let me illustrate:

```
library(ggplot2)

p <- ggplot(
  data=diamonds
 ,aes(
    x=carat
   ,y=price
  )
) +
geom_point() +
theme_bw()

is.ggplot(p)
# returns TRUE


p2 <- ggplot(
  data=diamonds
 ,aes(
    x=broken
   ,y=broken
  )
) +
geom_point() +
theme_bw()

is.ggplot(p2)
#also returns TRUE!

p2
#returns Error in eval(expr, envir, enclos) : object 'broken' not found 
```

right.  i think `ggplot_build()` is an alternative; take a look at [this commit](https://github.com/almartin82/mapvizieR/blob/8c4e25e95bed76f1eff4f8d0b093f8439e9f0c8f/R/fuzz_test.R#L39) where I examine the structure of the list object that comes back from ggplot_build and look for certain names (that I think are generic to all ggplot objects?  not sure about that, though).

I think this means we need to go through and strip out our `is.ggplot()` calls in tests?

**Comment by chrishaid** [comment]
You mean likes this:
https://github.com/almartin82/mapvizieR/blob/master/tests/testthat/test_elephants.R#L30-L31
(commited last week)

**Comment by almartin82** [comment]
that will test if the object claims to be class ggplot, but the disconnect
is that even a failed plot that threw an error will have class ggplot. It's
not wrong on its face, it just doesn't cover much of anything useful. But
it might _appear_ to at first glance. What does `str(p)` kick back? Maybe
an assertion on what is in str()?

(mobile)

**Comment by chrishaid** [comment]
Go one more line down in that link.

**Comment by chrishaid** [comment]
To line 32

**Comment by almartin82** [comment]
yes, exactly.  I think that we need to poke into the object and make sure that the guts match what we know should be there.  class name is necessary but certainly not sufficient.

i don't know enough about the structure of ggplot objects, but there might be some common elements that are common to every plot.  if that's the case, we could roll our own version of is.`is.ggplot()` that does something closer to the natural meaning.

**Comment by chrishaid** [comment]
For sure. I wrote a set of tests last week on a gg_build.  They must have gotten blown out at some point during a merge. I think the key data live in the plot section of the build object.

**Comment by chrishaid** [comment]
Ahh, here it is:
https://github.com/almartin82/mapvizieR/commit/6262e80af9239fbf2ee02d99aac5b71429e19f7d

**Comment by almartin82** [comment]
I think i had to ķill those because elephants has to do some munging on
terms (geom_density needs at least 3 observations) and as a consequence the
input length and output length weren't always the same.

**Comment by almartin82** [comment]
Yeah it was the sample that was the problem there. Sometimes it would
sample kids who would get munged-out by elephants. And then the test fails.

(mobile)
