### ISSUE TITLE
use the norm study data tables to look up testpercentile

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#45]
when doing longitudinal analysis, we want to make sure that we're using on set of norms, so that kids don't change percentiles simply because NWEA adopted a new norm conversion table (for instance, 2010 data uses the 2008 norms; 2012 data uses the 2011 norms).

We have `student_status_norms_2011` - the mapvizier object should look up RIT given grade/subject/season and return a percentile using that norm study.  @chrishaid thoughts?

**Comment by chrishaid** [comment]
`student_status_norms` are "attainment" norms, rather than growth, right?  That is, do they give your national percentile ranks?

**Comment by chrishaid** [comment]
If so, then yeah, I think you'd want to apply norms consistent regardless of when the norms were adopted (i.e., no abrupt changes).  We might want to reach out to NWEA to check on the thinking that the RIT scale itself remains stable acrossing norming periods; all that is really changing is the distribution of student achievement.

**Comment by almartin82** [comment]
yep those are the attainment norms - I am going to put those on the mapvizieR cdf this afternoon

**Comment by almartin82** [comment]
closed by pull request #50
