### ISSUE TITLE
roster prep should turn grade 13 into grade 0

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#5]
because grade 13 is stupid.

should be pretty simple.  do we write it as a stand alone function or make it a one-liner inside of `prep_roster` on [build status](https://github.com/almartin82/mapvizieR/blob/master/R/roster_prep.R)?  chris, your call.

**Comment by chrishaid** [comment]
I think we write a little util function.  Easier to write tests on that get's called in the prep_roster.

It should do two things (well, one thing really):
1. Check of 13 **or for K** and return 0
2. Recast variables to integer

**Comment by chrishaid** [comment]
The util function is complete.  Do you want to put it inside of prep_roster?
