### ISSUE TITLE
should we set examples to ## Not run:  ?

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#57]
According to [travis](https://travis-ci.org/almartin82/mapvizieR/builds/53989399#L1681) the code in our examples (mainly mapvizieR) is taking somewhere on the order of 1-2 minutes to run, minimum. 

That's not a problem _quite yet_ but our travis builds have been creeping up in time, and at some point they cut you off.  Chris -- how do you feel about putting long running examples into

```
## Not run:
...
## End(**Not run**)
```

jail?  on the plus side, faster CI builds! -- and it takes away a R-CMD note, which, you know, would be crantastic.  on the downside, if we're not testing our examples, they might drift from actual usage, which would be bad.

@chrishaid thoughts?

**Comment by chrishaid** [comment]
This issue is such a double edged sword.  I think if the example is essentially replicated in our tests, then why not put them in `Not run` jail?

**Comment by almartin82** [comment]
I wish there was an intermediate #dontrun that evaluated the parameter
names but didn't actually run the code.

(mobile)

**Comment by almartin82** [comment]
per the [last](https://travis-ci.org/almartin82/mapvizieR#L1738) travis build there are 4 examples that take more than 5 sec to run.  going to move those to 'not run'.
