### ISSUE TITLE
haid_plot: how should we categorize students with 0 points of rit growth?

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#79]
for haid_plot -- when kids get the EXACT same rit score in start/end, should their arrow head point forwards or backwards?  right now those kids are included in the 'negative' group (<=0).  thoughts?

**Comment by chrishaid** [comment]
I think of zero growth as a bad thing, which is why the get the "negative treatment": red arrow, red name, an X.

That said we could change the plot to a point (perhaps X shaped).  

c

**Comment by almartin82** [comment]
agreed here - keeping these red, as zero change over a year of school is not a good thing.
