### ISSUE TITLE
Capture fuzzy_tests RNG seed

### ISSUE THREAD

**Issue by chrishaid** [almartin82/mapvizieR#97]
So I ran the tests in the docker container that the [`becca_plot` build failed on](https://app.wercker.com/#build/554eb71f676bb8c31f11863b) and everything came back AOK.   So I ran them again. And everything came back AOK. 

I went back to the wercker and looked at the build log becca_plot failed in the fuzzy portion of the testthat script.  I even rebuilt the build, and not it passes and is ok to merge.

So I can't recreate whatever caused `becca_plot` to  barf :mask:

So, I think we need to report back what the random seed is if there is build failure caused by `fuzzy_test`.  The problem is the RNG seed is a 163 element long integer vector (it's stored as an attribute in the Global Env named `.Random.seed`.  But printing those characters to the build log seems like overkill and a pain to actually do anything with. 

Another option is for us to somehow set the seed randomly via `set.seed(seed)`and alway print that `seed` parameter o the console when running fuzzy test.  That way we should be able to recreate whatever random data.frame or vector caused the build failure.

Thoughts, @almartin82?

**Comment by chrishaid** [comment]
[Here's some food for thought on RNGs in R](http://r.789695.n4.nabble.com/How-to-obtain-seed-after-generating-random-number-td2336997.html)

**Comment by almartin82** [comment]
ahhhh - I was hoping that when we got the docket container back we'd see
detailed logs?

I have `fuzz_test` set to print the subset of students that failed, but
duh, the random number seed would deterministically produce those same
studentids.

Ideally we'd be able to see that ID in the wrecker log - perhaps set it,
print it, then test?

(mobile)

**Comment by chrishaid** [comment]
Yeah.  That's exactly what I'm thinking. 

—

**Comment by almartin82** [comment]
Cool - we can probably do that all inside of `fuzz_test`

(mobile)

**Comment by chrishaid** [comment]
Right.  The logs may be in the container. I didn't look for them too hard.  I'll take another looksy in the AM.  This docker stuff is kinda cool.

—

**Comment by almartin82** [comment]
bump

just ran into this again

(bumping for myself)
